// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8-i6v8N-vbUXeDZCIPa8yvI0D421xdFM',
    appId: '1:679584669339:web:b3d91b34ea73482a2eb03e',
    messagingSenderId: '679584669339',
    projectId: 'test-firestoredb-74471',
    authDomain: 'test-firestoredb-74471.firebaseapp.com',
    storageBucket: 'test-firestoredb-74471.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJEj_FhVJaOGNDBOttmCbkpy11sBfD8SU',
    appId: '1:679584669339:android:a558b0bf77d94d512eb03e',
    messagingSenderId: '679584669339',
    projectId: 'test-firestoredb-74471',
    storageBucket: 'test-firestoredb-74471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXn3R_s4jhUPjBvmSbbaNJyBZtl-ZK2CQ',
    appId: '1:679584669339:ios:bfb6a644ad9f05c42eb03e',
    messagingSenderId: '679584669339',
    projectId: 'test-firestoredb-74471',
    storageBucket: 'test-firestoredb-74471.appspot.com',
    iosClientId: '679584669339-kbgp0dd0ftijqfh3qut11dhs17p6g0j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXn3R_s4jhUPjBvmSbbaNJyBZtl-ZK2CQ',
    appId: '1:679584669339:ios:bfb6a644ad9f05c42eb03e',
    messagingSenderId: '679584669339',
    projectId: 'test-firestoredb-74471',
    storageBucket: 'test-firestoredb-74471.appspot.com',
    iosClientId: '679584669339-kbgp0dd0ftijqfh3qut11dhs17p6g0j0.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );
}
